### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by eson57** [dpurgin/harbour-callrecorder#17]
Hi,

Source line 23 in ui.ts do not translate. See screen below.
Great app btw. Thanks!

![screenshot-14-04-15-10-22-33](https://cloud.githubusercontent.com/assets/2996154/7133256/a3d9ca9e-e291-11e4-9d21-06bf67a34dc0.png)

**Comment by dpurgin** [comment]
Hi,

thanks for reporting, will check tonight.

Cheers

**Comment by dpurgin** [comment]
It seems to work fine with me! Downloaded your translation from Transifex. 

I think it could be marked as "unfinished", I sometimes just go through the .ts files with linguist and mark all strings as finished

![sailfishos emulator](https://cloud.githubusercontent.com/assets/8401313/7141919/847bbb98-e2f6-11e4-82fc-5f08f769f326.png)

**Comment by eson57** [comment]
Very strange! I've checked .ts file in both Linguist and my text editor, and there is nothing wrong. I also tried compiling and uploading new .qm file to phone, but I still have the same error.
Well, it's not that important. Something has gone corrupt in my phone, and will probably be corrected the next Call Recorder update.  ;)

**Comment by eson57** [comment]
As predicted... working fine in v0.5.1. Very tidy app, all in all.  :
