### ISSUE TITLE
Need info: Default storage location

### ISSUE THREAD

**Issue by adithyakhamithkar** [dpurgin/harbour-callrecorder#24]
Hi,

I would like to know what is the default storage path by mistake I changed it. So now all the recording come into my music player.

Could you please help me with this?
Thanks,

**Comment by eson57** [comment]
I think storage path doesn't really matter, because tracker puts all audio files in default music player.
If you have an SD card inserted,  default storage path is /media/sdcard/<sdcard ID>/Calls.

**Comment by adithyakhamithkar** [comment]
This was not happening before only after the change I noticed it. So if I
put it on the SD card the music player will not track it?


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>






On Sat, May 16, 2015 at 3:12 PM, Åke Engelbrektson <notifications@github.com

**Comment by eson57** [comment]
It will happen on SD card as well. At least it does on my device.

**Comment by adithyakhamithkar** [comment]
Let me try it out and let you know. Also when I delete the recording from the app they are still there in the default folder. Is this a bug?

**Comment by eson57** [comment]
Can't answer that. Hopefully, app author can sort this out for both of us.  ;)

**Comment by dpurgin** [comment]
@adithyakhamithkar 
The default path is /home/nemo/.local/share/kz.dpurgin/harbour-callrecorder/data but, as @eson57 says, it doesn't really matter where the recordings are, they are picked by the tracker. 

Regarding deletion issue, I've discovered a couple when working on automatic deletion of the old recordings. I'll introduce database consistency check later.

**Comment by adithyakhamithkar** [comment]
Let's wait to hear from him.

**Comment by adithyakhamithkar** [comment]
@dpurgin Thanks I would like to make a request if we can hide the recordings from being picked up from the tracker. Privacy would be at risk if one of the recordings would start to play.

**Comment by dpurgin** [comment]
@adithyakhamithkar can you please try this one: https://together.jolla.com/question/5935/how-to-blacklist-directories-from-being-indexed-by-tracker/

**Comment by adithyakhamithkar** [comment]
I will give it a try Thanks,

**Comment by dpurgin** [comment]
@adithyakhamithkar 
can you please tell if .nomedia file worked for you? On my second Jolla phone with default location setting (the one in ~/.local directory) the recordings do not appear in Media Player. In TJC discussion referenced above there was a post saying that tracker does not pick hidden directories, it seem to be true.

On the other hand, creating a .nomedia file didn't make any difference for me, the recordings that are located on SD card are still there in the Media Player

**Comment by adithyakhamithkar** [comment]
Yes after I switched to the default location it did not track the recording
in the media player.


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by dpurgin** [comment]
thanks

@eson57 could you please create an empty .nomedia file on your SD card location and see if the recordings would disappear from the  Media player?

**Comment by eson57** [comment]
Working on it at this moment  ;)

**Comment by adithyakhamithkar** [comment]
I have a request to make, Can we add a new feature of call and sms
filter/blocking ?


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by eson57** [comment]
@dpurgin No, didn't work!

**Comment by eson57** [comment]
Correction..
It actually seem to work, after I rebuilt media database and rebooted my device.
I will do some more testing...

**Comment by dpurgin** [comment]
@eson57 
I'm not really sure why .nomedia doesn't work. I've read on TJC that a directory containing .nomedia file will be excluded from mining. I've checked that I have this setting in gsettings but apparently touching bouth .nomedia file and a containing directory didn't make any difference. I've even tried creating another directory with .nomedia in it, then moved the recordings there but it didn't work as well. 

A file named backup.metadata workd instantly by the way. As soon as I touched a file named backup.metadata in my SD location, the recordings disappeared from Media player.

**Comment by dpurgin** [comment]
@adithyakhamithkar 

I think it should be another program :) Afaik it already exists in openrepos.

**Comment by eson57** [comment]
.nomedia definitely work after rebuilding database and reboot. So now we have two different ways of doing this.  :)

**Comment by adithyakhamithkar** [comment]
I did try looking at it found scumstopper and spcc. Not that great as your
app!


Adithya Khamithkar
[image: http://]about.me/adithyakhamithkar
<http://about.me/adithyakhamithkar?promo=email_sig>

**Comment by dpurgin** [comment]
Resolved, see #25
