### ISSUE TITLE
[Pre-Test] Daemon active failed in SailfishOS 1.1.6

### ISSUE THREAD

**Issue by TMavica** [dpurgin/harbour-callrecorder#29]
Loaded: loaded
Active: failed (Result: start-limit)
Process: 29223 ExecStart =/usr/bin/harbour-callrecorderd (code=exited, status=255)
Main PID: 29223

**Comment by dpurgin** [comment]
Is that version 0.5.1? 

Can you please upload or send me per email ~/.local/share/kz.dpurgin/harbour-callrecorder/log.txt? It contains phone numbers though which you might want to strip.

**Comment by TMavica** [comment]
yes. latest one

https://dl.dropboxusercontent.com/u/37229054/Log/log.txt

**Comment by dpurgin** [comment]
Thanks a lot. This was already noticed and fix was merged thanks to @rainisto (see [pull 22](../pull/22)). Your issue should be resolved if you compile and deploy the version from master branch, it would be the same as the latest public 0.5.1 but with Ofono check removed (though I didn't have a chance to check myself yet) or I could compile it myself for you tomorrow evening.

**Comment by TMavica** [comment]
combine for me, because I dont know programming. lol

**Comment by dpurgin** [comment]
All right, will do tomorrow evening. Good night :-)

**Comment by dpurgin** [comment]
@TMavica I've compiled it as version 0.5.2 and uploaded to https://dpurgin.github.io (direct link: https://dpurgin.github.io/releases/harbour-callrecorder/harbour-callrecorder-0.5.2-1.armv7hl.rpm ).

**Comment by TMavica** [comment]
Fixed.
thanks
