### ISSUE TITLE
Cant record private number in 0.52

### ISSUE THREAD

**Issue by TMavica** [dpurgin/harbour-callrecorder#30]
nothing show inside apps

**Comment by dpurgin** [comment]
Thanks for confirming, I saw this one some time ago but thought that the call recorder was off. Can you please send the log and tell the approximate time when you received the call? The log is at /home/nemo/.local/share/kz.dpurgin/harbour-callrecorder/log.txt

**Comment by dpurgin** [comment]
I've managed to reproduce it on my phone. Fixed for version 0.6
