### ISSUE TITLE
Chinese Char cant be show in recording list

### ISSUE THREAD

**Issue by TMavica** [dpurgin/harbour-callrecorder#31]
only number is show out, english dont have this problem

**Comment by dpurgin** [comment]
I think it might be #15. I've renamed one of my contacts and it worked like this:
![20150531121346](https://cloud.githubusercontent.com/assets/8401313/7908291/5fc4e538-0865-11e5-881e-e84b7ff73395.jpg)

**Comment by TMavica** [comment]
if ur contact name start with English word, example: CY 你好嗎，it cant show, but if all is chinese, 你好嗎， it shows number

**Comment by TMavica** [comment]
typo. CY 你好嗎 can show

**Comment by dpurgin** [comment]
Do you fill in both first and last names or use only one? I've put Chinese characters to both and it worked fine. Did you try renaming a contact who already was already displayed correctly in Call Recorder?

**Comment by TMavica** [comment]
only first name
I mean if the name combine with english and chinese, it can show. If only chinese, cant be show

**Comment by TMavica** [comment]
new version fixed
