### ISSUE TITLE
Can't install on SFOS 1.1.9.28

### ISSUE THREAD

**Issue by V10lator** [dpurgin/harbour-callrecorder#37]
![screenshot-20-09-15-13-40-58](https://cloud.githubusercontent.com/assets/1312422/9980541/e9ce4f1e-5f9d-11e5-85ed-38c0b1143f42.png)

**Comment by dpurgin** [comment]
Hi,

this is very strange. Do you have your internet connection on? What does the following command output:

`pkcon search name qt5-qtmultimedia-plugin-audio-pulseaudio`

**Comment by V10lator** [comment]
> pkcon refresh

did the trick. Thanks.
