### ISSUE TITLE
Second sim not get recorded

### ISSUE THREAD

**Issue by Bysmyyr** [dpurgin/harbour-callrecorder#57]
Calls from second simm do not get recorded at all. FIrst sim works fine.

**Comment by dpurgin** [comment]
Hi! Thanks for your input! This has been fixed in the upcoming update that will be released in a week or two.

**Comment by dpurgin** [comment]
Meanwhile you can try on of the recent test builds from this discussion

https://github.com/dpurgin/harbour-callrecorder/issues/53
