### ISSUE TITLE
Fatal Error : Nothing provides libQt5Contacts.so.5 

### ISSUE THREAD

**Issue by rajvalentino** [dpurgin/harbour-callrecorder#63]
Since , harbour-callrecorder-0.6.2-1.armv7hl.rpm hasn't recording the incoming voice , I tried installing 

[harbour-callrecorder-0.7.1-5.armv7hl.rpm](https://openrepos.net/sites/default/files/packages/4121/harbour-callrecorder-0.7.1-5.armv7hl.rpm)
--
which gives me Fatal error : nothing provides libQt5Contacts.so.5(Qt_5) needed by harbour-callrecorder-0.7.1-5.armv7hl

**Comment by almindor** [comment]
I just installed from rpm (0.7.2) directly via openrepos (not using warehouse) on the sony X and everything worked ok.

Maybe try refreshing your repos and check if you don't have some funky ones from warehouse. I had issues from Warehouse usage on my old Jolla.

**Comment by dpurgin** [comment]
The version 0.7.3 does not need this library anymore, please update from Openrepos.
